import "./globals.css";
import mongodbConnect from '@/backend/lib/mongodb'
import { GlobalProvider } from "./GlobalProvider"

export const metadata = {
  title: "REG-BOT",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await mongodbConnect()
  return (
    <html lang="en">
      <body>
        <GlobalProvider>
        {children}
        </GlobalProvider>
      </body>
    </html>
  );
}
